version: '3.8'
services:
  upfirstai_api_ts:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET='mysecret'
      - TOKEN_EXPIRY='3600'
      - LOG_LEVEL='info'
      - ENVIRONNEMENT='prod'
      - ENABLE_REDIRECT_PROCESSING='false'