name: Upfirst OAuth API CI/CD - Terraform

on:
  push:
    branches: [main-terraform]
  pull_request:
    branches: [main-terraform]

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: upfirstai_api_ts
  IMAGE_TAG: latest
  TERRAFORM_DIR: './terraform'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

  docker-scan-push:
    name: Docker Build & Security Scan
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::586794453336:role/GithubOIDCRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY/$ECR_REPOSITORY:$IMAGE_TAG \
            --label "git_sha=${{ github.sha }}" \
            --label "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" .

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  deploy-terraform:
    name: Terraform Deployment
    needs: docker-scan-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::586794453336:role/GithubOIDCRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: Terraform-${{ github.run_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform apply -input=false tfplan
        env:
          TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
          TF_VAR_ecr_repository: ${{ env.ECR_REPOSITORY }}
          TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
      
      - name: Deploy to ECS
        run: |
          # Update ECS task definition with new image
          TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition upfirstai-task)
          NEW_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities)')
          aws ecs register-task-definition --cli-input-json "$NEW_DEFINITION"
          
          # Update ECS service
          aws ecs update-service \
            --cluster upfirstai-cluster \
            --service upfirstai-service \
            --task-definition upfirstai-task \
            --force-new-deployment
          
          # Wait for deployment completion
          aws ecs wait services-stable \
            --cluster upfirstai-cluster \
            --services upfirstai-services
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          AWS_REGION: ${{ env.AWS_REGION }}

  cleanup:
    name: Cleanup (Failure)
    if: failure()
    needs: [docker-scan-push, deploy-terraform]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::586794453336:role/GithubOIDCRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: Terraform-${{ github.run_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.5.7
  
      - name: Terraform Destroy
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: |
          terraform init -input=false
          terraform destroy -auto-approve -input=false

      - name: Remove Docker images
        run: |
          docker rmi ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} || true